// automatically generated by the FlatBuffers compiler, do not modify

package schemas

const (
	///< US Dollars
	CurrencyUSD = 0
	///< Australian Dollars
	CurrencyAUD = 1
	///< Canadian Dollars
	CurrencyCAD = 2
	///< Swiss Francs
	CurrencyCHF = 3
	///< Euro
	CurrencyEUR = 4
	///< Pounds Sterling (UK)
	CurrencyGBP = 5
	///< Hong Kong Dollar
	CurrencyHKD = 6
	///< Japanese Yen
	CurrencyJPY = 7
)

var EnumNamesCurrency = map[int]string{
	CurrencyUSD:"USD",
	CurrencyAUD:"AUD",
	CurrencyCAD:"CAD",
	CurrencyCHF:"CHF",
	CurrencyEUR:"EUR",
	CurrencyGBP:"GBP",
	CurrencyHKD:"HKD",
	CurrencyJPY:"JPY",
}

