// automatically generated by the FlatBuffers compiler, do not modify

package schemas

const (
	OptionTypeput = 0
	OptionTypecall = 1
)

var EnumNamesOptionType = map[int]string{
	OptionTypeput:"put",
	OptionTypecall:"call",
}

