// automatically generated by the FlatBuffers compiler, do not modify

package schemas

const (
	SecurityTypeequity = 0
	SecurityTypefuture = 1
	SecurityTypeoption = 2
	SecurityTypeforex = 3
	SecurityTypeswap = 4
	SecurityTypebond = 5
)

var EnumNamesSecurityType = map[int]string{
	SecurityTypeequity:"equity",
	SecurityTypefuture:"future",
	SecurityTypeoption:"option",
	SecurityTypeforex:"forex",
	SecurityTypeswap:"swap",
	SecurityTypebond:"bond",
}

