// automatically generated by the FlatBuffers compiler, do not modify

package schemas

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SSB struct {
	_tab flatbuffers.Table
}

func GetRootAsSSB(buf []byte, offset flatbuffers.UOffsetT) *SSB {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SSB{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SSB) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SSB) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SSB) Entries(obj *SSBEntry, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *SSB) EntriesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func SSBStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SSBAddEntries(builder *flatbuffers.Builder, entries flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(entries), 0)
}
func SSBStartEntriesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func SSBEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
