// automatically generated by the FlatBuffers compiler, do not modify

package schemas

const (
	SymbolTypenormal = 0
	SymbolTypepreferred_stock = 1
	SymbolTypewarrant = 2
	SymbolTyperight = 3
	SymbolTypeunit = 4
	SymbolTypeindex = 5
	SymbolTypeintraday_nav = 6
	SymbolTypeprev_nav = 7
	SymbolTypemini = 8
	SymbolTypemini_settlement = 9
	SymbolTypepercent_open = 10
	SymbolTypeshares_outstanding = 11
	SymbolTypesettlement_value = 12
	SymbolTypetotal_cash_per_unit = 13
	SymbolTypedividend_ex_distribution = 14
	SymbolTypeaccumulative_dividend = 15
	SymbolTypeestimated_unit_cash = 16
)

var EnumNamesSymbolType = map[int]string{
	SymbolTypenormal:"normal",
	SymbolTypepreferred_stock:"preferred_stock",
	SymbolTypewarrant:"warrant",
	SymbolTyperight:"right",
	SymbolTypeunit:"unit",
	SymbolTypeindex:"index",
	SymbolTypeintraday_nav:"intraday_nav",
	SymbolTypeprev_nav:"prev_nav",
	SymbolTypemini:"mini",
	SymbolTypemini_settlement:"mini_settlement",
	SymbolTypepercent_open:"percent_open",
	SymbolTypeshares_outstanding:"shares_outstanding",
	SymbolTypesettlement_value:"settlement_value",
	SymbolTypetotal_cash_per_unit:"total_cash_per_unit",
	SymbolTypedividend_ex_distribution:"dividend_ex_distribution",
	SymbolTypeaccumulative_dividend:"accumulative_dividend",
	SymbolTypeestimated_unit_cash:"estimated_unit_cash",
}

