// automatically generated by the FlatBuffers compiler, do not modify

package fb

const (
	IssueTypenormal      = 0
	IssueTypepreferred   = 1
	IssueTypewarrant     = 2
	IssueTyperight       = 3
	IssueTypeunit        = 4
	IssueTypenon_voting  = 5
	IssueTypemini        = 6
	IssueTypewhen_issued = 7
	IssueTypeother       = 8
)

var EnumNamesIssueType = map[int]string{
	IssueTypenormal:      "normal",
	IssueTypepreferred:   "preferred",
	IssueTypewarrant:     "warrant",
	IssueTyperight:       "right",
	IssueTypeunit:        "unit",
	IssueTypenon_voting:  "non_voting",
	IssueTypemini:        "mini",
	IssueTypewhen_issued: "when_issued",
	IssueTypeother:       "other",
}
