// automatically generated by the FlatBuffers compiler, do not modify

package fb

const (
	///< No Exchange
	MICNONE = 0
	///< NASDAQ (Used for displayed trades/quotes)
	MICXNAS = 1
	///< New York Stock Exchange
	MICXNYS = 2
	///< NYSE Alternext (Formerly American Stock Exchange)
	MICXASE = 3
	///< Chicago Board of Options Exchange
	MICCBOE = 4
	///< NYSE ARCA (Formerly ArcaEx, Archipelago Exchange)
	MICARCX = 5
	///< National Stock Exchange (Formerly Cincinatti Stock Exchange)
	MICXCIS = 6
	///< NASDAQ OMX PHLX (Formerly Philadelphia Stock Exchange)
	MICXPHL = 7
	///< Options Pricing Reporting Authority
	MICOPRA = 8
	///< NASDAQ OMX BX (Formerly BSE, Boston Stock Exchange)
	MICXBOS = 9
	///< NASDAQ Global/Select (Listing MIC for securities meeting all of NASDAQ's listing requirements. Quotes/trades reported by XNAS)
	MICXNGS = 10
	///< NASDAQ Capital Market (Listing MIC for small-cap securities meeting streamlined requirements. Quotes/trades reported by XNAS)
	MICXNCM = 11
	///< BATS Trading
	MICBATS = 12
	///< BATS Trading Y-Exchange
	MICBATY = 13
	///< Direct Edge Exchange (Operated by BATS Trading)
	MICEDGE = 14
	///< Direct Edge X Exchange (Operated by BATS Trading)
	MICEDGX = 15
	///< Chicago Stock Exchange
	MICXCHI = 16
	///< OTC Bulletin Board (Operated by NASDAQ)
	MICXOTC = 17
	///< Direct Edge A Exchange
	MICEDGA = 18
	///< SMART Order Router (Non-MIC)
	MICSMART = 19
	///< ISLAND ECN
	MICICEL = 20
	///< Investors Exchange (IEX)
	MICIEX = 21
	///< SIP (Standard Information Processor)
	MICSIP = 22
)

var EnumNamesMIC = map[int]string{
	MICNONE:  "NONE",
	MICXNAS:  "XNAS",
	MICXNYS:  "XNYS",
	MICXASE:  "XASE",
	MICCBOE:  "CBOE",
	MICARCX:  "ARCX",
	MICXCIS:  "XCIS",
	MICXPHL:  "XPHL",
	MICOPRA:  "OPRA",
	MICXBOS:  "XBOS",
	MICXNGS:  "XNGS",
	MICXNCM:  "XNCM",
	MICBATS:  "BATS",
	MICBATY:  "BATY",
	MICEDGE:  "EDGE",
	MICEDGX:  "EDGX",
	MICXCHI:  "XCHI",
	MICXOTC:  "XOTC",
	MICEDGA:  "EDGA",
	MICSMART: "SMART",
	MICICEL:  "ICEL",
	MICIEX:   "IEX",
	MICSIP:   "SIP",
}
