// automatically generated by the FlatBuffers compiler, do not modify

package fb

const (
	QuoteConditionnone                           = 0
	QuoteConditionregular                        = 1
	QuoteConditionactive                         = 2
	QuoteConditioninactive                       = 3
	QuoteConditionexchange_best                  = 4
	QuoteConditionconsolidated_best              = 5
	QuoteConditionlocked                         = 6
	QuoteConditioncrossed                        = 7
	QuoteConditiondepth                          = 8
	QuoteConditionfast_trading                   = 9
	QuoteConditionnon_firm                       = 10
	QuoteConditionmanual                         = 11
	QuoteConditionoutright_price                 = 12
	QuoteConditionimplied_price                  = 13
	QuoteConditiondepth_on_offer                 = 14
	QuoteConditiondepth_on_bid                   = 15
	QuoteConditiondepth_on_bid_offer             = 16
	QuoteConditionclosing                        = 17
	QuoteConditionnews                           = 18
	QuoteConditiontrading_range                  = 19
	QuoteConditionorder_influx                   = 20
	QuoteConditiondue_to_related                 = 21
	QuoteConditionnews_pending                   = 22
	QuoteConditionadditional_info                = 23
	QuoteConditionadditional_info_due_to_related = 24
	QuoteConditionresume                         = 25
	QuoteConditionview_of_common                 = 26
	QuoteConditionvolume_alert                   = 27
	QuoteConditionorder_imbalance                = 28
	QuoteConditionequipment                      = 29
	QuoteConditionno_open_resume                 = 30
	QuoteConditionregular_eth                    = 31
	QuoteConditionauto_exec                      = 32
	QuoteConditionauto_exec_eth                  = 33
	QuoteConditionfast_market_eth                = 34
	QuoteConditioninactive_eth                   = 35
	QuoteConditionrotation                       = 36
	QuoteConditionrotation_eth                   = 37
	QuoteConditionhalt                           = 38
	QuoteConditionhalt_eth                       = 39
	QuoteConditiondue_to_news                    = 40
	QuoteConditiondue_to_news_pending            = 41
	QuoteConditiontrading_resume                 = 42
	QuoteConditionout_of_seq                     = 43
	QuoteConditionbid_specialist                 = 44
	QuoteConditionoffer_specialist               = 45
	QuoteConditionbid_offer_specialist           = 46
	QuoteConditionend_of_day_sam                 = 47
	QuoteConditionforbidden_sam                  = 48
	QuoteConditionfrozen_sam                     = 49
	QuoteConditionpre_opening_sam                = 50
	QuoteConditionopening_sam                    = 51
	QuoteConditionopen_sam                       = 52
	QuoteConditionsurveillance_sam               = 53
	QuoteConditionsuspended_sam                  = 54
	QuoteConditionreserved_sam                   = 55
	QuoteConditionno_active_sam                  = 56
	QuoteConditionrestricted                     = 57
)

var EnumNamesQuoteCondition = map[int]string{
	QuoteConditionnone:                           "none",
	QuoteConditionregular:                        "regular",
	QuoteConditionactive:                         "active",
	QuoteConditioninactive:                       "inactive",
	QuoteConditionexchange_best:                  "exchange_best",
	QuoteConditionconsolidated_best:              "consolidated_best",
	QuoteConditionlocked:                         "locked",
	QuoteConditioncrossed:                        "crossed",
	QuoteConditiondepth:                          "depth",
	QuoteConditionfast_trading:                   "fast_trading",
	QuoteConditionnon_firm:                       "non_firm",
	QuoteConditionmanual:                         "manual",
	QuoteConditionoutright_price:                 "outright_price",
	QuoteConditionimplied_price:                  "implied_price",
	QuoteConditiondepth_on_offer:                 "depth_on_offer",
	QuoteConditiondepth_on_bid:                   "depth_on_bid",
	QuoteConditiondepth_on_bid_offer:             "depth_on_bid_offer",
	QuoteConditionclosing:                        "closing",
	QuoteConditionnews:                           "news",
	QuoteConditiontrading_range:                  "trading_range",
	QuoteConditionorder_influx:                   "order_influx",
	QuoteConditiondue_to_related:                 "due_to_related",
	QuoteConditionnews_pending:                   "news_pending",
	QuoteConditionadditional_info:                "additional_info",
	QuoteConditionadditional_info_due_to_related: "additional_info_due_to_related",
	QuoteConditionresume:                         "resume",
	QuoteConditionview_of_common:                 "view_of_common",
	QuoteConditionvolume_alert:                   "volume_alert",
	QuoteConditionorder_imbalance:                "order_imbalance",
	QuoteConditionequipment:                      "equipment",
	QuoteConditionno_open_resume:                 "no_open_resume",
	QuoteConditionregular_eth:                    "regular_eth",
	QuoteConditionauto_exec:                      "auto_exec",
	QuoteConditionauto_exec_eth:                  "auto_exec_eth",
	QuoteConditionfast_market_eth:                "fast_market_eth",
	QuoteConditioninactive_eth:                   "inactive_eth",
	QuoteConditionrotation:                       "rotation",
	QuoteConditionrotation_eth:                   "rotation_eth",
	QuoteConditionhalt:                           "halt",
	QuoteConditionhalt_eth:                       "halt_eth",
	QuoteConditiondue_to_news:                    "due_to_news",
	QuoteConditiondue_to_news_pending:            "due_to_news_pending",
	QuoteConditiontrading_resume:                 "trading_resume",
	QuoteConditionout_of_seq:                     "out_of_seq",
	QuoteConditionbid_specialist:                 "bid_specialist",
	QuoteConditionoffer_specialist:               "offer_specialist",
	QuoteConditionbid_offer_specialist:           "bid_offer_specialist",
	QuoteConditionend_of_day_sam:                 "end_of_day_sam",
	QuoteConditionforbidden_sam:                  "forbidden_sam",
	QuoteConditionfrozen_sam:                     "frozen_sam",
	QuoteConditionpre_opening_sam:                "pre_opening_sam",
	QuoteConditionopening_sam:                    "opening_sam",
	QuoteConditionopen_sam:                       "open_sam",
	QuoteConditionsurveillance_sam:               "surveillance_sam",
	QuoteConditionsuspended_sam:                  "suspended_sam",
	QuoteConditionreserved_sam:                   "reserved_sam",
	QuoteConditionno_active_sam:                  "no_active_sam",
	QuoteConditionrestricted:                     "restricted",
}
