// automatically generated by the FlatBuffers compiler, do not modify

package fb

const (
	TradeConditionnone                      = 0
	TradeConditionregular                   = 1
	TradeConditioncash                      = 2
	TradeConditionavg_price                 = 3
	TradeConditioncash_trade                = 4
	TradeConditionnext_day_market           = 5
	TradeConditionopening_detail            = 6
	TradeConditionintraday_detail           = 7
	TradeConditionrule_127                  = 8
	TradeConditionrule_155                  = 9
	TradeConditionsold_last                 = 10
	TradeConditionnext_day                  = 11
	TradeConditionopened                    = 12
	TradeConditionseller                    = 13
	TradeConditionsold                      = 14
	TradeConditionstopped_stock             = 15
	TradeConditionimbalance_more_buyers     = 16
	TradeConditionimbalance_more_sellers    = 17
	TradeConditionopening_price             = 18
	TradeConditionmanual                    = 19
	TradeConditioniso                       = 20
	TradeConditionbargain_condition         = 21
	TradeConditionconverted_price_indicator = 22
	TradeConditionexchange_last             = 23
	TradeConditionfinal_price               = 24
	TradeConditionex_pit                    = 25
	TradeConditioncrossed                   = 26
	TradeConditioncancel                    = 27
	TradeConditionvolume_only               = 28
	TradeConditiondirect_plus               = 29
	TradeConditionacquisition               = 30
	TradeConditionbunched                   = 31
	TradeConditiondistribution              = 32
	TradeConditionbunched_sale              = 33
	TradeConditionsplit                     = 34
	TradeConditioncancel_stopped            = 35
	TradeConditioncancel_eth                = 36
	TradeConditioncancel_stopped_eth        = 37
	TradeConditionout_of_seq_eth            = 38
	TradeConditioncancel_last_eth           = 39
	TradeConditionsold_last_eth             = 40
	TradeConditioncancel_last               = 41
	TradeConditionsold_last_sale            = 42
	TradeConditioncancel_open               = 43
	TradeConditioncancel_open_eth           = 44
	TradeConditionopened_sale_eth           = 45
	TradeConditioncancel_only               = 46
	TradeConditioncancel_only_eth           = 47
	TradeConditionlate_open_eth             = 48
	TradeConditionauto_exec_eth             = 49
	TradeConditionreopen                    = 50
	TradeConditionreopen_eth                = 51
	TradeConditionadjusted                  = 52
	TradeConditionadjusted_eth              = 53
	TradeConditionspread                    = 54
	TradeConditionspread_eth                = 55
	TradeConditionstraddle                  = 56
	TradeConditionstraddle_eth              = 57
	TradeConditionstopped                   = 58
	TradeConditionstopped_eth               = 59
	TradeConditionregular_eth               = 60
	TradeConditioncombo                     = 61
	TradeConditioncombo_eth                 = 62
	TradeConditionclosing                   = 63
	TradeConditionprior_ref                 = 64
	TradeConditionstopped_sold_last         = 65
	TradeConditionstopped_out_of_seq        = 66
	TradeConditionfast_market               = 67
	TradeConditionauto_exec                 = 68
	TradeConditionform_t                    = 69
	TradeConditionbasket_idx                = 70
	TradeConditionburst_basket              = 71
)

var EnumNamesTradeCondition = map[int]string{
	TradeConditionnone:                      "none",
	TradeConditionregular:                   "regular",
	TradeConditioncash:                      "cash",
	TradeConditionavg_price:                 "avg_price",
	TradeConditioncash_trade:                "cash_trade",
	TradeConditionnext_day_market:           "next_day_market",
	TradeConditionopening_detail:            "opening_detail",
	TradeConditionintraday_detail:           "intraday_detail",
	TradeConditionrule_127:                  "rule_127",
	TradeConditionrule_155:                  "rule_155",
	TradeConditionsold_last:                 "sold_last",
	TradeConditionnext_day:                  "next_day",
	TradeConditionopened:                    "opened",
	TradeConditionseller:                    "seller",
	TradeConditionsold:                      "sold",
	TradeConditionstopped_stock:             "stopped_stock",
	TradeConditionimbalance_more_buyers:     "imbalance_more_buyers",
	TradeConditionimbalance_more_sellers:    "imbalance_more_sellers",
	TradeConditionopening_price:             "opening_price",
	TradeConditionmanual:                    "manual",
	TradeConditioniso:                       "iso",
	TradeConditionbargain_condition:         "bargain_condition",
	TradeConditionconverted_price_indicator: "converted_price_indicator",
	TradeConditionexchange_last:             "exchange_last",
	TradeConditionfinal_price:               "final_price",
	TradeConditionex_pit:                    "ex_pit",
	TradeConditioncrossed:                   "crossed",
	TradeConditioncancel:                    "cancel",
	TradeConditionvolume_only:               "volume_only",
	TradeConditiondirect_plus:               "direct_plus",
	TradeConditionacquisition:               "acquisition",
	TradeConditionbunched:                   "bunched",
	TradeConditiondistribution:              "distribution",
	TradeConditionbunched_sale:              "bunched_sale",
	TradeConditionsplit:                     "split",
	TradeConditioncancel_stopped:            "cancel_stopped",
	TradeConditioncancel_eth:                "cancel_eth",
	TradeConditioncancel_stopped_eth:        "cancel_stopped_eth",
	TradeConditionout_of_seq_eth:            "out_of_seq_eth",
	TradeConditioncancel_last_eth:           "cancel_last_eth",
	TradeConditionsold_last_eth:             "sold_last_eth",
	TradeConditioncancel_last:               "cancel_last",
	TradeConditionsold_last_sale:            "sold_last_sale",
	TradeConditioncancel_open:               "cancel_open",
	TradeConditioncancel_open_eth:           "cancel_open_eth",
	TradeConditionopened_sale_eth:           "opened_sale_eth",
	TradeConditioncancel_only:               "cancel_only",
	TradeConditioncancel_only_eth:           "cancel_only_eth",
	TradeConditionlate_open_eth:             "late_open_eth",
	TradeConditionauto_exec_eth:             "auto_exec_eth",
	TradeConditionreopen:                    "reopen",
	TradeConditionreopen_eth:                "reopen_eth",
	TradeConditionadjusted:                  "adjusted",
	TradeConditionadjusted_eth:              "adjusted_eth",
	TradeConditionspread:                    "spread",
	TradeConditionspread_eth:                "spread_eth",
	TradeConditionstraddle:                  "straddle",
	TradeConditionstraddle_eth:              "straddle_eth",
	TradeConditionstopped:                   "stopped",
	TradeConditionstopped_eth:               "stopped_eth",
	TradeConditionregular_eth:               "regular_eth",
	TradeConditioncombo:                     "combo",
	TradeConditioncombo_eth:                 "combo_eth",
	TradeConditionclosing:                   "closing",
	TradeConditionprior_ref:                 "prior_ref",
	TradeConditionstopped_sold_last:         "stopped_sold_last",
	TradeConditionstopped_out_of_seq:        "stopped_out_of_seq",
	TradeConditionfast_market:               "fast_market",
	TradeConditionauto_exec:                 "auto_exec",
	TradeConditionform_t:                    "form_t",
	TradeConditionbasket_idx:                "basket_idx",
	TradeConditionburst_basket:              "burst_basket",
}
